insert into user values (1, 'Joe', 'Coyne', 'jcoyne', 'supersecret1', 'joe@mail.com');
insert into user values (2, 'Fred', 'Hensen', 'fhensen', 'supersecret2', 'fred@mail.com');
insert into user values (3, 'ying', 'kot', 'key', 'my', 'fvi@mail.com');
insert into user values (4, 'hi', 'ko', 'y', 'ji', 'ji@mail.com');
insert into user_roles values (1, 'admin', 'jcoyne', 1);
insert into user_roles values (2, 'user', 'fhensen', 2);
insert into user_roles values (3, 'user', 'my', 3);
insert into user_roles values (4, 'user', 'ji', 4);
insert into contact values (1, 'Fred', 'Hensen','fred@mail.com', 'hi1', 'message1', 2, 'fhensen');
insert into contact values (2, 'ying', 'kot', 'fvi@mail.com', 'hi2', 'message2', 3, 'key');
insert into contact values (3, 'hi', 'ko', 'fvi@mail.com', 'hi3', 'message3', 4, 'y');
insert into donation values (1, 40, 1, '10-11-20', 'funShot');
insert into donation values (2, 20, 2, '10-11-20', 'funShot');
insert into donation values (3, 50, 1, '10-11-20', 'funShot');
insert into events values (1,'professional','matc','2020-11-19','01:32','Enjoy the event together here!');
insert into events values (2,'Couple shot','MononaLake','2020-11-28','01:32','Bring your couple and joy us');
insert into events values (3,'funPhoto','capital','2020-11-28','01:32','Join us with the fun photo');
insert into events values (4,'funto','house','2020-11-28','01:32','Join us');
insert into events_user values  (2, 3);
# insert into events_user values (2, 2);
# insert into events_user values (2, 3);
